steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image', '.' ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml', '--image-url', 'gcr.io/iconic-hue-273619/quickstart-image']
  timeout: '200s'
images:
- 'gcr.io/$PROJECT_ID/quickstart-image'